apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: online-event-booking-haiderzia
data:
  DATABASE_URL_USER: "postgres://postgres:@postgres:5432/userdb"
  DATABASE_URL_BOOKING: "postgres://postgres:@postgres:5432/bookingdb"
  MONGO_URI: "mongodb://mongo-db:27017/eventsDB"
  RABBITMQ_URL: "amqp://rabbitmq"
  USER_SERVICE_URL: "http://user-service:5001"
  EVENT_SERVICE_URL: "http://event-service:5001"
  BOOKING_SERVICE_URL: "http://booking-service:5002"
